### PR TITLE
Update to use the langchain-neo4j package

### PR DESCRIPTION
**Pull request by alexthomas93**
- Adds `langchain-neo4j` to requirements
- Updates all other requirements to their latest version
- Replaces `langchain_community` imports for `Neo4jVector`, `Neo4jGraph`, `Neo4jChatMessageHistory`, `GraphCypherQAChain` with their `langchain_neo4j` equivalents

### CODE REVIEW

**Comment by martinohanlon** [comment]
Thanks @alexthomas93 

I did a quick search through the `courses` repo to see if `langchain_community` was referenced for the course. There is only 1 place which is for documentation. e.g. https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.neo4j_vector.Neo4jVector.html

Is there a `langchain_neo4j` equivalent?

**Comment by alexthomas93** [comment]
> Thanks @alexthomas93
> 
> I did a quick search through the `courses` repo to see if `langchain_community` was referenced for the course. There is only 1 place which is for documentation. e.g. https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.neo4j_vector.Neo4jVector.html
> 
> Is there a `langchain_neo4j` equivalent?

@martinohanlon PR [here](https://github.com/neo4j-graphacademy/courses/pull/284) for the `courses` repo. I think I've updated all the links but let me know if I've missed any. There will always be a `langchain_neo4j` equivalent.

**Comment by martinohanlon** [comment]
Running the solution, I get the following error / warning.

```
ValueError: In order to use this chain, you must acknowledge that it can make dangerous requests by setting `allow_dangerous_requests` to `True`.You must narrowly scope the permissions of the database connection to only include necessary permissions. Failure to do so may result in data corruption or loss or reading sensitive data if such data is present in the database.Only use this chain if you understand the risks and have taken the necessary precautions. See https://python.langchain.com/docs/security for more information.
```

Are there alternative solutions to this?

```
cypher_qa = GraphCypherQAChain.from_llm(
    llm,
    graph=graph,
    verbose=True,
    cypher_prompt=cypher_prompt,
    allow_dangerous_requests=True,
)
```

Fine if not but we should include some information / precautions in the course text. Read-only user, etc

**Comment by alexthomas93** [comment]
> allow_dangerous_requests=True,

@martinohanlon There's no alternative right now. This was actually added in a previous version of the community package which was carried over to the langchain-neo4j package so I'm a bit surprised the previous code was even working

**Comment by martinohanlon** [comment]
>I'm a bit surprised the previous code was even working

The current version uses an older version of the `langchain_community` package. I tag package versions in `requirements.txt` to mitigate these sort of issue cropping up.

**Comment by martinohanlon** [comment]
Merging into `llm-updates` to progress

**Pull request merged**
